// ============================================
// seed.js — Bulk Insert 50 Premium Products
// Run with: node seed.js
// ============================================

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const products = [

  // ─── TAPS (14 items) ───────────────────────────────────────────
  {
    id: 1,
    name: 'Prestige Gold Single-Lever Basin Tap',
    category: 'Taps',
    price: 4999,
    description: 'Elegant gold-finish single-lever tap with ceramic disc technology. Smooth flow control and drip-free performance for premium bathrooms.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 40,
  },
  {
    id: 2,
    name: 'Chrome Waterfall Basin Tap',
    category: 'Taps',
    price: 3599,
    description: 'Contemporary waterfall-style chrome tap creating a dramatic visual statement. Quiet cascade flow, anti-splash design.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 35,
  },
  {
    id: 3,
    name: 'Matte Black Wall-Mount Tap',
    category: 'Taps',
    price: 5499,
    description: 'Sophisticated matte black wall-mount design. Solid brass body with quarter-turn ceramic cartridge for lasting durability.',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format',
    stock: 22,
  },
  {
    id: 4,
    name: 'Brushed Nickel Pillar Tap Set',
    category: 'Taps',
    price: 2999,
    description: 'Classic pillar tap set in brushed nickel finish. Hot/cold pair, easy installation, corrosion-resistant coating.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format',
    stock: 50,
  },
  {
    id: 5,
    name: 'Rose Gold Sensor-Touch Kitchen Tap',
    category: 'Taps',
    price: 8999,
    description: 'Smart sensor-touch kitchen tap in luxurious rose gold. Hands-free activation, 360° swivel spout, LED temperature indicator.',
    image_url: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&auto=format',
    stock: 18,
  },
  {
    id: 6,
    name: 'Vintage Brass Crosshead Bath Tap',
    category: 'Taps',
    price: 6299,
    description: 'Antique-inspired crosshead bath tap in unlacquered brass. Develops a natural patina over time, solid heritage construction.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 15,
  },
  {
    id: 7,
    name: 'Stainless Steel Pull-Out Kitchen Tap',
    category: 'Taps',
    price: 5199,
    description: 'Multi-function pull-out spray kitchen tap in brushed stainless steel. Dual spray/stream modes, 360° rotation.',
    image_url: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&auto=format',
    stock: 30,
  },
  {
    id: 8,
    name: 'Gunmetal Grey Thermostatic Bar Mixer',
    category: 'Taps',
    price: 11499,
    description: 'Precision thermostatic mixer tap in gunmetal grey. Maintains preset temperature within ±1°C, ideal for safety and comfort.',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format',
    stock: 12,
  },
  {
    id: 9,
    name: 'White Ceramic Lever Basin Tap',
    category: 'Taps',
    price: 3199,
    description: 'Minimalist white ceramic lever tap, moisture-resistant finish. Ideal for modern Scandinavian-style bathrooms.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 45,
  },
  {
    id: 10,
    name: 'Copper Artisan Freestanding Bath Tap',
    category: 'Taps',
    price: 14999,
    description: 'Handcrafted artisan copper tap for freestanding baths. Each piece is unique with a hand-hammered finish.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 8,
  },
  {
    id: 11,
    name: 'Chrome Deck-Mount Bidet Tap',
    category: 'Taps',
    price: 2299,
    description: 'Compact chrome deck-mount bidet tap with adjustable flow rate. Easy single-hole installation.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format',
    stock: 60,
  },
  {
    id: 12,
    name: 'Polished Chrome High-Arc Kitchen Tap',
    category: 'Taps',
    price: 4299,
    description: 'High-arc gooseneck kitchen tap in polished chrome. Extra clearance for large pots, single-hole mounting.',
    image_url: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&auto=format',
    stock: 28,
  },
  {
    id: 13,
    name: 'Brushed Gold Concealed Shower Valve',
    category: 'Taps',
    price: 9799,
    description: 'In-wall concealed thermostatic shower valve in brushed gold. Dual outlet control, compatible with all shower heads.',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format',
    stock: 14,
  },
  {
    id: 14,
    name: 'Matte White Mono Bloc Basin Mixer',
    category: 'Taps',
    price: 3899,
    description: 'Sleek mono bloc basin mixer in matte white. Single-hole fitting, pop-up waste included.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 33,
  },

  // ─── WASHBASINS (13 items) ─────────────────────────────────────
  {
    id: 15,
    name: 'Carrara Marble Vessel Washbasin',
    category: 'Washbasins',
    price: 22999,
    description: 'Hand-carved Carrara marble vessel basin. Each piece features unique natural veining, a true statement of luxury.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 6,
  },
  {
    id: 16,
    name: 'Semi-Recessed Ceramic Oval Basin',
    category: 'Washbasins',
    price: 8499,
    description: 'Elegant semi-recessed oval basin in vitreous china. Overflow protection, single tap hole, gloss white finish.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 20,
  },
  {
    id: 17,
    name: 'Matte Black Countertop Round Basin',
    category: 'Washbasins',
    price: 11299,
    description: 'Bold matte black round countertop basin. Scratch-resistant nano-coat finish, pairs perfectly with chrome or gold taps.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 16,
  },
  {
    id: 18,
    name: 'Wall-Hung Rectangular Vanity Basin',
    category: 'Washbasins',
    price: 7299,
    description: 'Space-saving wall-hung rectangular basin in gloss white. Concealed fixing kit included, weight-tested to 150kg.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format',
    stock: 25,
  },
  {
    id: 19,
    name: 'Teak Wood & Ceramic Integrated Basin',
    category: 'Washbasins',
    price: 18499,
    description: 'Designer basin combining teak wood surround with inset ceramic bowl. Sealed wood treatment, ideal for spa bathrooms.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 9,
  },
  {
    id: 20,
    name: 'Double Bowl Vanity Unit Basin',
    category: 'Washbasins',
    price: 15999,
    description: 'Extra-wide double-bowl vanity basin in soft white. Perfect for master bathrooms shared by couples.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 11,
  },
  {
    id: 21,
    name: 'Copper Hammered Vessel Basin',
    category: 'Washbasins',
    price: 16799,
    description: 'Artisan hand-hammered copper vessel basin. Each piece is one-of-a-kind, develops rich patina with age.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 7,
  },
  {
    id: 22,
    name: 'Slimline Cloakroom Compact Basin',
    category: 'Washbasins',
    price: 4299,
    description: 'Space-efficient compact cloakroom basin, perfect for powder rooms. Only 36cm wide, overflow included.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format',
    stock: 40,
  },
  {
    id: 23,
    name: 'Stone Resin Deep Soaking Basin',
    category: 'Washbasins',
    price: 19999,
    description: 'Luxurious deep stone resin basin in warm taupe. Heat-retaining surface, anti-bacterial material composition.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 5,
  },
  {
    id: 24,
    name: 'Integrated Storage Vanity Basin Unit',
    category: 'Washbasins',
    price: 24999,
    description: 'All-in-one vanity basin with two drawer storage unit. Soft-close drawers, moisture-proof carcass, gloss white.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 13,
  },
  {
    id: 25,
    name: 'Triangular Corner Washbasin',
    category: 'Washbasins',
    price: 5899,
    description: 'Clever corner-fit triangular basin for awkward bathroom layouts. Gloss white, single tap hole, wall-mounted.',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format',
    stock: 30,
  },
  {
    id: 26,
    name: 'Concrete Effect Rectangular Basin',
    category: 'Washbasins',
    price: 9299,
    description: 'Industrial-chic concrete-effect ceramic basin. Resin surface, lightweight, stain-resistant, no sealing required.',
    image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&auto=format',
    stock: 18,
  },
  {
    id: 27,
    name: 'Backlit LED Mirror Basin Set',
    category: 'Washbasins',
    price: 29999,
    description: 'Premium basin and backlit LED mirror set. Demister pad, touch-dimmer, anti-fog glass mirror, IP44 rated.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    stock: 4,
  },

  // ─── PIPES & FITTINGS (12 items) ──────────────────────────────
  {
    id: 28,
    name: 'CPVC Hot & Cold Pipe 15mm × 3m',
    category: 'Pipes',
    price: 349,
    description: 'High-quality CPVC pipe suitable for both hot and cold water. Temperature range: -40°C to 93°C, pressure-rated.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 200,
  },
  {
    id: 29,
    name: 'Stainless Steel Corrugated Flexible Hose',
    category: 'Pipes',
    price: 699,
    description: 'Heavy-duty corrugated stainless steel flexible hose. 500mm length, ½" BSP fittings, handles thermal expansion.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 150,
  },
  {
    id: 30,
    name: 'PPR Fusion Weld Pipe 25mm × 4m',
    category: 'Pipes',
    price: 549,
    description: 'Premium PPR pipe for domestic plumbing. Fusion-weld joints, non-corroding, smooth inner bore reduces scale build-up.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 180,
  },
  {
    id: 31,
    name: 'Chrome Plated Brass Elbow 90°',
    category: 'Pipes',
    price: 199,
    description: 'Heavy-duty chrome-plated brass 90° elbow. ½" female threads both ends, pressure tested to 15 bar.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 300,
  },
  {
    id: 32,
    name: 'uPVC Soil Pipe 110mm × 3m',
    category: 'Pipes',
    price: 1299,
    description: 'Heavy-duty uPVC soil pipe for drainage. Solvent weld ring seal socket, BS EN1329 compliant, grey.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 100,
  },
  {
    id: 33,
    name: 'Brass Gate Valve 20mm',
    category: 'Pipes',
    price: 449,
    description: 'Full-bore brass gate valve, 20mm compression ends. Used for main supply isolation, lead-free brass body.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 120,
  },
  {
    id: 34,
    name: 'Flexible Braided Tap Connector 30cm',
    category: 'Pipes',
    price: 249,
    description: 'Stainless-steel braided flexible tap connector. Burst-resistant, 30cm length, ½" BSP fittings, easy installation.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 250,
  },
  {
    id: 35,
    name: 'Push-Fit Equal Tee 22mm',
    category: 'Pipes',
    price: 179,
    description: 'Tool-free push-fit equal tee for copper or plastic pipe. Suitable for hot and cold water systems up to 95°C.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 350,
  },
  {
    id: 36,
    name: 'Copper Press-Fit Straight Coupling 15mm',
    category: 'Pipes',
    price: 159,
    description: 'Professional copper press-fit coupling. Approved for gas and water, WRAS approved, M-press profile.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 400,
  },
  {
    id: 37,
    name: 'Anti-Vibration Pump Connector Pair',
    category: 'Pipes',
    price: 899,
    description: 'Rubber-lined anti-vibration connectors for boiler pump connections. Reduces noise transfer, ¾" BSP threads.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 75,
  },
  {
    id: 38,
    name: 'Float Ball Valve ½" Heavy Duty',
    category: 'Pipes',
    price: 379,
    description: 'High-capacity float ball valve for header tanks and cisterns. Adjustable float arm, brass body, ½" BSP.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 130,
  },
  {
    id: 39,
    name: 'Polyethylene Underground Water Pipe 32mm',
    category: 'Pipes',
    price: 799,
    description: 'Blue MDPE underground water supply pipe. 32mm × 25m coil, UV-resistant, suitable for potable water.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format',
    stock: 60,
  },

  // ─── SWITCHES & SOCKETS (11 items) ────────────────────────────
  {
    id: 40,
    name: 'Brushed Steel 1-Gang Dimmer Switch',
    category: 'Switches',
    price: 1299,
    description: 'Premium brushed steel leading-edge dimmer switch. 400W capacity, compatible with LED and halogen, screwless faceplate.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 80,
  },
  {
    id: 41,
    name: 'Gold 2-Gang 13A Switched Socket',
    category: 'Switches',
    price: 1899,
    description: 'Opulent gold flat-plate 2-gang socket. USB-A + USB-C charging ports (3.1A total), shuttered for child safety.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 65,
  },
  {
    id: 42,
    name: 'Matt Black Smart WiFi Switch',
    category: 'Switches',
    price: 2499,
    description: 'App-controlled smart switch in premium matt black. Works with Alexa & Google Home, energy monitoring, timer schedules.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 55,
  },
  {
    id: 43,
    name: 'Antique Bronze 2-Way Light Switch',
    category: 'Switches',
    price: 949,
    description: 'Victorian-style antique bronze toggle switch. Solid brass toggle, suitable for staircase and landing 2-way wiring.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 90,
  },
  {
    id: 44,
    name: 'Polished Chrome USB Shaver Socket',
    category: 'Switches',
    price: 2199,
    description: 'Dual-voltage shaver socket in polished chrome. 110/240V auto-select, IP44 rated for bathrooms, recessed installation.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 45,
  },
  {
    id: 45,
    name: 'Pearl White 4-Gang Grid Switch Plate',
    category: 'Switches',
    price: 1599,
    description: 'Modular 4-gang grid switch plate in gloss white. Mix and match modules: switches, dimmers, USB, data sockets.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 70,
  },
  {
    id: 46,
    name: 'Stainless Steel IP66 Outdoor Socket',
    category: 'Switches',
    price: 2899,
    description: 'Heavy-duty weatherproof outdoor socket. IP66-rated, stainless steel, lockable cover, 13A RCD protected.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 38,
  },
  {
    id: 47,
    name: 'Glass Touch Panel Light Switch',
    category: 'Switches',
    price: 3499,
    description: 'Ultra-modern capacitive glass touch switch. LED backlit, 1/2/3 gang options, tempered glass surface, works with smart home.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 30,
  },
  {
    id: 48,
    name: 'Brass Bell Push Doorbell Switch',
    category: 'Switches',
    price: 799,
    description: 'Traditional solid brass bell push for door entry. Engraved "Press" lettering, surface mount, 5A rated, lacquered finish.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 100,
  },
  {
    id: 49,
    name: 'Chrome 20A DP Switch with LED Indicator',
    category: 'Switches',
    price: 1099,
    description: 'Heavy-duty 20A double-pole switch for appliances. Neon indicator light, polished chrome, for boilers, immersions, cookers.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 85,
  },
  {
    id: 50,
    name: 'Wireless Remote Control Switch Kit',
    category: 'Switches',
    price: 1799,
    description: 'RF remote-control switch kit. 30m range through walls, no rewiring, works with standard lighting circuits, 2-channel receiver.',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format',
    stock: 55,
  },
];

// ─── Insert Products ──────────────────────────────────────────────
async function seedProducts() {
  console.log(`🚀 Seeding ${products.length} products into Supabase...`);

  const { data, error } = await supabase
    .from('products')
    .upsert(products, { onConflict: 'id' });

  if (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }

  console.log(`✅ Successfully seeded ${products.length} products!`);
  console.table(
    products.map(p => ({ id: p.id, name: p.name, category: p.category, price: `₹${p.price}`, stock: p.stock }))
  );
}

seedProducts();